services:
  - type: web
    name: transport-token-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push && node seed.js
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: transport-token-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://transport-token-client.onrender.com
    healthCheckPath: /health

  - type: web
    name: transport-token-client
    runtime: node
    region: frankfurt
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://transport-token-api.onrender.com

  - type: web
    name: transport-token-admin
    runtime: node
    region: frankfurt
    plan: free
    rootDir: admin
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://transport-token-api.onrender.com

databases:
  - name: transport-token-db
    plan: free
    region: frankfurt
    databaseName: transport_token
